version: '2.1'

services:
  golang-gqlgen-graphql-upload-example:
    image: golang-gqlgen-graphql-upload-example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8080:8080
